### ISSUE TITLE
Capitalisation excessive dans le `<title>` ?

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/sirene_as_api_front#122]
Le `<title>` du site est “Entreprise.data.gouv.fr”, je me serais attendu à “entreprise.data.gouv.fr”, qui me semble être le nom du site / produit

**Comment by Samuelfaure** [comment]
C'est un choix très personnel mais IMHO la capitalisation rend le nom du produit plus esthétique.

**Comment by gregoirenovel** [comment]
OK, note juste que https://transport.data.gouv.fr/ et https://transport.data.gouv.fr/ ont a priori fait le choix d'utiliser une minuscule.
