### ISSUE TITLE
Ne pas afficher de pagination dans le cas où les résultats de recherche rentrent sur une page

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/sirene_as_api_front#129]
Ex : https://entreprise.data.gouv.fr/search?fullText=2%20rue%20jacques%20louvel%20tessier&page=1

La pagination semble superflue ("Précédent" et "Suivant" étant inactifs)

**Comment by giglemad** [comment]
Le fait de documenter le paramètre page même en cas de page unique favorise la découverte de la pagination
