### ISSUE TITLE
La partie de la home sur l'interrogation de l'API est trompeuse

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/sirene_as_api_front#133]
On lit :
> Vous pouvez, si vous le souhaitez, interroger directement l'API Sirene
> [Documentation de l'API]

Quand je lis ça ETQ dev, je pense que :
- il existe une API Sirene sur laquelle je peux taper directement
- cliquer sur le bouton va m'emmener sur une page de doc d'API (genre https://doc.entreprise.api.gouv.fr/)

Or ces deux suppositions sont fausses.

Remanier le texte pour mieux expliquer ce dont il s'agit ?

**Comment by Samuelfaure** [comment]
Le bouton ramène en fait effectivement sur la page de doc de l'API en sandbox : https://sandbox.entreprise.data.gouv.fr/api_doc

Cela sera push sur production dès que la page sera finie (le responsive est encore défectueux)
