### ISSUE TITLE
Le lien sur la home vers le site de l'API Entreprise n'est plus le bon

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/sirene_as_api_front#134]
On pointe vers `https://www.apientreprise.fr/` au lieu de `https://entreprise.api.gouv.fr/`

**Comment by Samuelfaure** [comment]
Note : penser à harmoniser le lien sur la page home et sur la page de doc

**Comment by Samuelfaure** [comment]
fixed in 1ff82d719d098531d31c9329750d51601b6a63b9
