### ISSUE TITLE
Lier le bouton "Données de référence" directement à la base Sirene

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/sirene_as_api_front#136]
Pour le moment ça pointe vers https://www.data.gouv.fr/fr/reference, pointer directement vers https://www.data.gouv.fr/fr/datasets/base-sirene-des-entreprises-et-de-leurs-etablissements-siren-siret/ ?

**Comment by gregoirenovel** [comment]
Note : dans le footer, on pointe bien directement vers la base

**Comment by Samuelfaure** [comment]
Après réflexion je préfère laisser le lien de la page de présentation pointer vers le sommaire des références data.gouv car cela permet de présenter le Service Public de la Donnée sans pour autant perdre l'utilisateur (le lien vers la base sirène étant bien visible sur ce sommaire)
